### ISSUE TITLE
Remove ayuco added comment in Main.php

### ISSUE THREAD

**Issue by amostajo** [10quality/wpmvc-commands#39]
@garretthyder What do you think about this?

Do you find useful having Ayuco adding a comment every time it adds something to the `Main.php` class?

See example:
```php
        // Ayuco: addition 2020-01-16 06:54 am
        $this->add_action('init', 'ActionController@init');
```

Not sure if we should keep this for audit purposes or not.

**Comment by garretthyder** [comment]
Hi @amostajo 

When starting with the framework and commands for ayuco I did find this useful in that it helped me find the injected commands. That being said I would then go and replace the comment with my own to explain what the entry is for.

So maybe leave it there but add an additional option for providing a comment;
`--comment="Admin Controller for adding settings..."`
*This could be used not only in Main.php where the entry is added but in the case of Model/View/Controller files that are generated it could be used as the main comment there instead of just `AdminController controller.`

**Comment by amostajo** [comment]
Supported options in different commands:

* `--comment="..."`
* `--audit`
* `--void`

I will add documentation on the website later.
